language: node_js
node_js:
  - "8.9"
  # - 10

cache: yarn

script:
  - mocha test/*.coffee
  - istanbul report text-summary lcov

after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'

services:
  - redis-server

addons:
  apt:
    update: true
